name: Bandit Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install Bandit
      - name: Install Bandit
        run: pip install bandit

      # Step 4: Run Bandit scan on vuln.py
      - name: Run Bandit scan
        id: bandit_scan
        run: |
          bandit vuln.py --format json --output bandit-report.json || true
          CRITICAL_COUNT=$(grep -c '"issue_severity": "CRITICAL"' bandit-report.json || true)
          echo "critical_count=$CRITICAL_COUNT" >> $GITHUB_ENV

      # Step 5: Upload Bandit report as an artifact
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.json

      # Step 6: Block PR if Critical Vulnerabilities Found
      - name: Block Pull Request
        if: env.critical_count > 0
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Security Scan Failed**
            Critical vulnerabilities were found in `vuln.py`. PR is blocked.

      # Step 7: Fail Workflow if Critical Issues Exist
      - name: Fail Workflow if Critical Issues Exist
        if: env.critical_count > 0
        run: exit 1

      # Step 8: Comment Success if No Critical Vulnerabilities Found
      - name: Successful Scan Comment
        if: env.critical_count == 0
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Security Scan Successful**
            No Critical vulnerabilities were found in `vuln.py`. PR is approved.

      # Step 9: Auto-Merge Pull Request
      - name: Auto-Merge Pull Request
        if: env.critical_count == 0
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
