name: Bandit Security Scan

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  security-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        id: bandit_scan
        run: |
          bandit vuln.py --format json --output bandit-report.json || true
          CRITICAL_COUNT=$(grep -c '"issue_severity": "HIGH"' bandit-report.json || true)
          echo "critical_count=$CRITICAL_COUNT" >> $GITHUB_ENV

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.json

      - name: Debug Critical Count
        run: echo "Critical Count is ${{ env.critical_count }}"

      - name: Auto-Merge Pull Request
        if: ${{ env.critical_count != '' && fromJSON(env.critical_count) == 0 }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT if GITHUB_TOKEN fails
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
